### ISSUE TITLE
Jenkinsの設定ファイル、ジョブを全てコードで管理したい(可能かどうか)

### ISSUE THREAD

**Issue by sunakan** [sunakan/dice#30]
親 #28

**Comment by sunakan** [comment]
Jenkins Configuration as Code：最初の一歩（ママ見て、すごいでしょ）
20 9月, 2018  in jenkins  tagged configuration as code / JCasC / Jenkins

https://cloudbees.techmatrix.jp/jenkins-configuration-code-look-ma-no-hands/

**Comment by sunakan** [comment]
Jenkins のシステム設定を yaml で書けるようにする Configuration as Code プラグイン
https://www.kaizenprogrammer.com/entry/2018/09/23/030646

**Comment by sunakan** [comment]
サンプル
https://github.com/Praqma/praqma-jenkins-casc

**Comment by sunakan** [comment]
Jenkins Configuration as Code：プラグインをどう扱うか
https://cloudbees.techmatrix.jp/jenkins-configuration-code-plugins/

**Comment by sunakan** [comment]
![default](https://user-images.githubusercontent.com/43210698/53880399-3872f800-4054-11e9-979a-b512b3a67ecc.PNG)

**Comment by sunakan** [comment]
プラグインを使わずやってる

Jenkinsのジョブをソースコードとしてバージョン管理したい
https://qiita.com/megmogmog1965/items/9f2fb16dfe9d3db97946

リポジトリ
https://github.com/megmogmog1965/version-controlled-jenkins

**Comment by sunakan** [comment]
- configuration as codeプラグインを入れてみる

**Comment by sunakan** [comment]
時間かかりそうなので、やめる
プラグイン使わない方向で

**Comment by sunakan** [comment]
/var/jenkins_home/jobs/
マウントしてあげれば解決しそう

**Comment by sunakan** [comment]
docker-compose.ymlに追記
diceジョブのconfig.xmlを追加

```
...
  jenkins:
    image: jenkins/jenkins:lts-slim
    ports:
      - 8080:8080
    volumes:
      - .:/dice
      - ./containers/jenkins/jenkins_home/jobs:/var/jenkins_home/jobs
```

**Comment by sunakan** [comment]
```
実はシステム設定についてもこれまでにコード化しようとする取り組みはありました。
例えば、JENKINS_HOME に init.groovy という groovy スクリプトを置くと Jenkins の起動時にスクリプトを実行することができる仕組みがあります。
```

とりあえず、これでいいからやりたい

**Comment by sunakan** [comment]
config.xmlだけでは駄目だった
jenkinsのダッシュボードに出てこない

![default](https://user-images.githubusercontent.com/43210698/53882123-ce108680-4058-11e9-8332-1579050e387e.PNG)

**Comment by sunakan** [comment]
/var/run/docker.sock:/var/run/docker.sock
のマウント設定でDockerが動くのか試す
Windowsでは動かんと書いてあるけど、vagrant&VirtualBoxのUbuntuだから大丈夫だと信じる

**Comment by sunakan** [comment]
docker-compose command not foundそれはそうだ

**Comment by sunakan** [comment]
sudo gpasswd -a jenkins docker
...
この時点でJenkins専用のDockerfileとdocker-compose.ymlを作るべきか？

**Comment by sunakan** [comment]
移行方法あった
タグからconfiguration as code が消えてる

https://cloudbees.techmatrix.jp/jenkins-configuration-code-migration/

**Comment by sunakan** [comment]
GitとPipeline、Pipeline:StageView、Configuration as codeプラグイン(選んだのは4つ依存プラグインは知らない)
Configuration as codeで[Jenkinsの設定] => 舌にスクロール => [Configuration as code] => Export Configurationボタンをクリック => ダウンロード


```
plugins:
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
security:
  remotingCLI:
    enabled: false
unclassified:
  location:
    url: "http://192.168.33.13:8080/"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    defaultProperties:
    - installSource:
        installers:
        - jdkInstaller:
            acceptLicense: false
```
